# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

xcodeproj 'MRFoundation iOS Example'
workspace '../../Remote Foundation'
use_frameworks!

target 'MRFoundation iOS Example' do
    pod 'CocoaAsyncSocket'
end

