# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

xcodeproj 'MRFoundation OS X Example'
workspace '../../Remote Foundation'
use_frameworks!

target 'MRFoundation OS X Example' do
    pod 'CocoaAsyncSocket'
end

